### ISSUE TITLE
Error: Unable to resolve action `DependencyTrack/gh-upload-bom@v1.0.0`, repository not found

### ISSUE THREAD

**Issue by toivo-app** [DependencyTrack/gh-upload-sbom#1]
Hi,

I'm getting the error **Error: Unable to resolve action `DependencyTrack/gh-upload-bom@v1.0.0`, repository not found** when trying to use this action.

This is my complete job:
```
jobs:
  dtrack:
    name: DependencyTrack
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.9
      - name: Create BOM
        id: create-bom
        uses: CycloneDX/gh-node-module-generatebom@master
      - name: Upload BOM
        uses: DependencyTrack/gh-upload-bom@master
        with:
          serverhostname: 'api-dtrack.toivo.app'
          apikey: ${{ secrets.DTRACK_API_KEY }}
          projectname: 'Toivo Mobile'
          projectversion: ${{ steps.branch-name.outputs.current_branch }}
```
