### ISSUE TITLE
Action stuck after successful upload

### ISSUE THREAD

**Issue by simonknittel** [DependencyTrack/gh-upload-sbom#26]
I'm having the issue that after the upload finished, the action gets stuck and doesn't stop. It will run forever until it gets canceled by an action wide timeout.

My workflow file:
```yml
name: sbom-grafana

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sbom-grafana.yml

jobs:
  generate_and_upload:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: anchore/sbom-action@v0.15.10
        with:
          image: grafana/grafana-oss:10.4.1
          artifact-name: sbom.cdx.json
          output-file: sbom.cdx.json
          format: cyclonedx-json

      - uses: DependencyTrack/gh-upload-sbom@v3.0.0
        with:
          serverhostname: my-hostname
          apikey: ${{ secrets.DTRACK_APIKEY }}
          project: my-project-id
          bomfilename: sbom.cdx.json

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: sbom.cdx.json
          path: sbom.cdx.json
```

The logs look like this:
```
Run DependencyTrack/gh-upload-sbom@master
Reading BOM: sbom.cdx.json...
Uploading to Dependency-Track server my-hostname...
Response status code:
Finished uploading BOM to Dependency-Track server.
Error: The operation was canceled.
```
![image](https://github.com/DependencyTrack/gh-upload-sbom/assets/8451099/8d7db5f6-d637-429f-832d-42b5c449f314)

Notably, the `Response status code:` is empty. Also, I can confirm that the upload finished successfully since Dependency Track shows me the correct date for _Last BOM Import_.

Any idea what is happening?
